services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.1.0
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis_cache
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      
volumes:
  db_data:
  redis_data:
