services:
    consul:
        image: hashicorp/consul
        ports:
            - "8500:8500" # Consul web UI and API
            - "8600:8600/udp" # DNS server
        command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
