services:
    db:
        image: postgres:17.4
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning

volumes:
    postgres_data:
