# .github/workflows/integration-tests.yml
name: Integration Tests

on:
  push:
    paths:
      - 'testcontainers/**'
  pull_request:
    paths:
      - 'testcontainers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install -r testcontainers/requirements.txt
    
    - name: Run integration tests
      run: pytest -v
